[build]
  command = "npm install && npm run build:client && npm run build:functions"
  publish = "client/build"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  [functions.index]
    timeout = 30

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200